name: Build

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Dependencies
        run: |
          vcpkg integrate install
          vcpkg install sdl2:x64-windows

      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          msbuild /target:sprite /property:Configuration=Release sprite.sln

      - name: Collect
        run: |
          mkdir upload
          move bin\Release\sprite.exe upload
          move bin\Release\SDL2.dll upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: sprite-windows
          path: upload

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev

      - name: Setup
        run: |
          mkdir sprite/build

      - name: Build
        run: |
          cd sprite/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-10 ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv sprite/build/sprite upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: sprite-linux
          path: upload

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Dependencies
        run: brew install sdl2

      - name: Setup
        run: |
          mkdir sprite/build

      - name: Build
        run: |
          cd sprite/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-10 ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv sprite/build/sprite upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: sprite-macos
          path: upload
